### ISSUE TITLE
C/CRに搭載されている加速度センサについて

### ISSUE THREAD

**Issue by ghost** [WHILL/whill_control_system_protocol_specification#1]
本機種に搭載されている加速度センサについて

現在、電動車いすの加速度センサを用いて車いすの前後の加速度および旋回（横方向）加速度を求め、値を使用したいと考えています。
以前、公式上では、「Model CR搭載のIMUは精度が低く、ロボティクス的な利用には厳しいため、利用は非推奨とさせていただいております。」とありますが、具体的に教えていただくこと可能でしょうか？

推奨しない理由
・加速度センサ自体の精度がよくないのか
・センサの取り付け位置がよくないのか
・プログラムとセンサの相性がよくないのか
など、あれば教えていただきたいです。

お手数をおかけしますが、何卒よろしくお願いいたします。

**Comment by s-katsu** [comment]
お問い合わせありがとうございます。

大きく2つ理由があります。

1．精度
ご記載いただいた通り、ロボット制御に持ちいるには期待する精度が出せない可能性があるためです。
例えば低速なモビリティの制御で期待できるような分解能が満たせるかは用途や、利用される側の求められるスペックによるのですが、それを保証することが難しいため、IMUとしては外部に別途用いていただくことを推奨させていただいております。
結局利用される側でIMUとして必要なスペックは異なってくるため、ご自身でご用意していただき、そちらを利用していただくことを推奨させていただいております。

２．センサー取付位置
こちらは通信仕様書に記載されている通り、水平に取り付けられておらず、通信上はセンサーが機体に対して斜めのような方向のデータとして出力されています。
機体の進行方向などに加速度がセンサー値(X,Y,Z)として直接取れないため、ご利用を推奨しておりません。

![image](https://user-images.githubusercontent.com/20053970/197999339-abfda219-6ba8-4c94-9627-5078bb0e8517.png)

**Comment by ghost** [comment]
ご回答いただきありがとうございます。

使用者の求めるスペックであるかはわからないということなので、
値が上手く取得できなければ、外付けを検討しようと思います。センサの取り位置は計算で求めることが出来るので問題ございません。

追記質問
コマンドでの制御の際に、前後の加速度および横方向の加速度の値を教えていただくことは可能でしょうか。

**Comment by s-katsu** [comment]
> 追記質問
> コマンドでの制御の際に、前後の加速度および横方向の加速度の値を教えていただくことは可能でしょうか

申し訳ございませんが、もう少し詳細を教えていただけますでしょうか。
機体が走行している際の加速度は、機体の加減速の状態、例えばそれまで停止していた状態から加速しているのか、一定速度で走行しているか、減速しているかなどによって常に変化し続けるため、一定の値になることはございませんので、ある条件においての値をお伝えすることは難しいです。

**Comment by ghost** [comment]
コマンド操作時の最高加速度が知りたいので、停止している状態からの前後左右加速度になります。

よろしくお願いいたします。

**Comment by s-katsu** [comment]
> コマンド操作時の最高加速度が知りたいので、停止している状態からの前後左右加速度になります。

前回の回答でお伝えした通りですが、加速度の値は機体の加速・減速の具合によって一定ではありませんので、一概に数値をお答えすることは難しいです。
もし何か動作させて、ある加速度をしきい値として判断されたいのであれば、Model CRで実際の加速度の値を見つつ、検証していただくかたちとなります。
これは加速度の値を機体内蔵のセンサーを使っても、外付けのセンサーを使っても、同等の対応が必要となります。
