### ISSUE TITLE
TXD-RXD間の電圧について

### ISSUE THREAD

**Issue by useuse01** [WHILL/whill_control_system_protocol_specification#2]
毎々お世話になっております。

ModelCRの問い合わせでこちらを紹介されたので、以下内容教えていただきたく。

・車いす制御用ケーブルコネクタのBATTの3端子の電源側にヒューズがついているという認識であっていますでしょうか？
・車いす制御用ケーブルコネクタのTXD-RXD間の電圧を測定した所、DCで約28Vだったのですが正しい電圧でしょうか？

車いす本体に改造は行っておらず、電圧はケーブルコネクタの負荷側を端子受けして測定しております。
他にスイッチング電源など接続しておらず、PLC、TP、ブレーカをBATT-GND間に接続しております。

以上、お手数ですがよろしくお願いいたします。

**Comment by s-katsu** [comment]
大変申し訳ありません、Model_CRの問い合わせは

https://github.com/WHILL/Model_CR_Technical_Support

側でお願いできますでしょうか？

弊社の案内が間違っており大変申し訳ございませんが、上記のリポジトリで再度Issue起票をお願いいたします。
同じ内容をご投稿いただければ構いません。
こちらはCloseさせていただきます。
