### ISSUE TITLE
WHILLのキーボード操作のROSによる実装について

### ISSUE THREAD

**Issue by ryo0616** [WHILL/whill_control_system_protocol_specification#3]
現在，私はWHILL model CRのキーボード操作をROSにより実装したいと考えています．しかし，サイトなどで調べてもその方法がよくわからない状況です．
そこで，WHILLのキーボード操作をROSで実装する方法があれば教えていただきたいです．

お手数をおかけしますが，よろしくお願いします．

**Comment by s-katsu** [comment]
大変申し訳ありません、Model_CRの問い合わせは

https://github.com/WHILL/Model_CR_Technical_Support

側でお願いできますでしょうか？
本リポジトリは通信仕様に関するリポジトリであるためです。

弊社の案内が間違っており大変申し訳ございませんが、上記のリポジトリで再度Issue起票をお願いいたします。
同じ内容をご投稿いただければ構いません。
こちらはCloseさせていただきます。
