### ISSUE TITLE
Whillの片流れ防止機能について

### ISSUE THREAD

**Issue by sazanami-sazanami** [WHILL/whill_control_system_protocol_specification#4]
以前購入したWhill model CRを使用しております。

ご質問なのですが、
貴社HP（https://whill.inc/jp/model-c）
において、
Whill modelCには片流れ防止機能があると記載があります。
片流れ防止機能について、以下の内容にてご質問させていただきたく存じます。
１）modelCRにも搭載されていますでしょうか。
２）modelC/CRともに、モデル初期から搭載されていますでしょうか。
３）片流れ防止はどのようにして行われていますでしょうか。例えば、ジャイロセンサを利用してヨー軸角速度を0にする、あるいはIMU情報にカルマンフィルタに通して姿勢推定を行い、機体姿勢を制御する、といった制御方法についてです。
４）片流れ防止機能はいつ作動するでしょうか。例えば、ロール軸方向にどれくらい傾いたときか、あるいは平面でも（３）の方法の制御が常に作動しているのか。また、進路によって作動するかどうか変わるか。すなわち、直進しているときだけなのか、直進＋旋回（ジョイスティックを右上／左上に倒したような状態）でも作動するか。
５）片流れ防止機能の性能はどれくらいでしょうか。すなわち、どれくらいの横断勾配まで対応しており、どれくらいの直進性が得られるか。

以上ご回答いただけますと幸いです。

**Comment by s-katsu** [comment]
大変申し訳ありません、Model_CRの問い合わせは

https://github.com/WHILL/Model_CR_Technical_Support

側でお願いできますでしょうか？

弊社の案内が間違っており大変申し訳ございませんが、上記のリポジトリで再度Issue起票をお願いいたします。
同じ内容をご投稿いただければ構いません。
こちらはCloseさせていただきます。
